### ISSUE TITLE
Capella cluster provision types error

### ISSUE THREAD

**Issue by vharkusha-bridgewise** [couchbasecloud/terraform-provider-couchbase-capella#242]
Hi, 

Took provider to provision a CouchBase Capella cluster. But for some reason faced error below.  My environment configuration:

- Arch: Arm64 (macos Sequoia 15.1)
- Terraform version: `1.9.8`
- Provider version: `1.3.0`

```
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to couchbase-capella_cluster.cluster["app-general-cluster"], provider "provider[\"registry.terraform.io/couchbasecloud/couchbase-capella\"]" produced an unexpected new value: .service_groups: planned set element
│ cty.ObjectVal(map[string]cty.Value{"node":cty.ObjectVal(map[string]cty.Value{"compute":cty.ObjectVal(map[string]cty.Value{"cpu":cty.NumberIntVal(4), "ram":cty.NumberIntVal(16)}),
│ "disk":cty.ObjectVal(map[string]cty.Value{"autoexpansion":cty.True, "iops":cty.NumberIntVal(3000), "storage":cty.NumberIntVal(50), "type":cty.StringVal("gp3")})}), "num_of_nodes":cty.NumberIntVal(1),
│ "services":cty.SetVal([]cty.Value{cty.StringVal("data"), cty.StringVal("index"), cty.StringVal("query")})}) does not correlate with any element in actual.
│ 
```

Affected resource: 
```
resource "couchbase-capella_cluster" "cluster" {
  for_each         = var.couchbase_clusters_params
  organization_id  = lookup(each.value, "org_id", local.couchbase_org_id[var.env])
  project_id       = lookup(each.value, "project_id", couchbase-capella_project.project.id)
  name             = "${var.env}-${each.key}-${each.value.cloud_provider.region}"
  description      = lookup(each.value, "description", "")
  couchbase_server = {
    version = "7.6"
  }
  cloud_provider = each.value.cloud_provider
  service_groups =  [{
      node = {
        compute = {
          cpu = 4
          ram = 16
        }
        disk = {
          type          = "gp3"
          autoexpansion = true
          storage       = 50
          iops          = 3000
        }
      }
      num_of_nodes = 1
      services     = ["data", "index", "query"]
    }]
  availability   = {
    type = each.value.availability_type
  }
  support = each.value.support
```

Thanks

**Comment by vharkusha-bridgewise** [comment]
P.S.
Cluster defined by resource created, but terraform said we must replace existed cluster with new one

**Comment by cdsre** [comment]
Generally when I see these issues in other providers its because the value in the state file changed during the apply. A lot of providers will set the intial state in response to creating the resource, and then do a look up of the resource and set the state again. 

This validates that the resource does exist in the target system and is handy in solutions where the response is asynchronous. Like in the case of cluster creation, Terraform will call the API to create the cluster and will get a response immediately. 
At this point the state file is set with cluster ID and plan. 

The provider then goes into a loop and keeps polling for the cluster to complete. It will then retrieve the current state of the cluster.

It will then look through each of the service groups it retrieved from the current cluster status and compare it with the service group in the plan. I suspect your cluster response is not coming back with the service group or comes back with something different. 

```go
	clusterResponse := clusterapi.GetClusterResponse{}
	err = json.Unmarshal(response.Body, &clusterResponse)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Cluster",
			errorMessageWhileClusterCreation+"error during unmarshalling:"+err.Error(),
		)
		return
	}

	diags = resp.State.Set(ctx, initializePendingClusterWithPlanAndId(plan, clusterResponse.Id.String()))
...
...
        err = c.checkClusterStatus(ctx, organizationId, projectId, clusterResponse.Id.String())
...
...
	refreshedState, err := c.retrieveCluster(ctx, organizationId, projectId, clusterResponse.Id.String())
...
...

	for i, serviceGroup := range refreshedState.ServiceGroups {
		if clusterapi.AreEqual(plan.ServiceGroups[i].Services, serviceGroup.Services) {
			refreshedState.ServiceGroups[i].Services = plan.ServiceGroups[i].Services
		}
	}

	// Set state to fully populated data
	diags = resp.State.Set(ctx, refreshedState)
```

While your cluster may be up terraform will have tainted the resource in your state file as incomplete so it will want to destroy and recreate it.  Does this error happen on every apply or does it work sometimes? Also can you show your nodes and services of the cluster like

![image](https://github.com/user-attachments/assets/c5556acf-e518-4779-b31a-98bffe30f34c)
![image](https://github.com/user-attachments/assets/50751d1d-d045-4000-b58e-50988848a713)
